# Makefile
Default:
    id: 0
    foreground: 000000
    background: ffffff
Comment:
    id: 1
    foreground: 3f7f5f
    background: ffffff
Preprocessor:
    id: 2
    foreground: 7f7f9f
    background: ffffff
    style: [ bold ]
Identifier:
    id: 3
    foreground: 0000c0
    background: ffffff
Operator:
    id: 4
    foreground: 000000
    background: ffffff
Target:
    id: 5
    foreground: 3f5fbf
    background: ffffff
Ideol:
    id: 9
    foreground: 000000
    background: ffffff
